# Generated by Django 6.0.6 on 2026-07-20 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_existing_users_as_admin(apps, schema_editor):
    """Existing users become admin so current operators keep full access."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("accounts", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={"role": "admin"},
        )


def unseed_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0021_position_inventory_lines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("booking_operator", "Booking operator"),
                            ("port_operator", "Port operator"),
                            ("viewer", "Viewer"),
                        ],
                        default="booking_operator",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="UserPortAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_access",
                        to="catalogs.port",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username", "port__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "port"),
                        name="accounts_unique_user_port_access",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_existing_users_as_admin, unseed_user_profiles),
    ]
