# Generated by Django 6.0.3 on 2026-03-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Puerto',
                'verbose_name_plural': 'Puertos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imo', models.CharField(blank=True, max_length=20)),
                ('capacity_pax', models.PositiveIntegerField(blank=True, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Barco',
                'verbose_name_plural': 'Barcos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Naviera',
                'verbose_name_plural': 'Navieras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity_pax', models.PositiveIntegerField(blank=True, null=True)),
                ('max_draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berths', to='docking.port')),
            ],
            options={
                'verbose_name': 'Muelle',
                'verbose_name_plural': 'Muelles',
                'ordering': ['port', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pax_count', models.PositiveIntegerField(blank=True, null=True)),
                ('berth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='docking.berth')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='docking.port')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='docking.ship')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-date', 'port', 'ship'],
            },
        ),
        migrations.AddField(
            model_name='ship',
            name='shipping_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='docking.shippingline'),
        ),
    ]
