# Generated by Django 6.0.3 on 2026-03-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docking', '0002_add_scale_crew_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='code',
            field=models.CharField(blank=True, help_text='Clave catálogo, ej. HAL ZUIDERDAM, RCI VISION', max_length=80),
        ),
        migrations.AddField(
            model_name='shippingline',
            name='fee_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PortFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_tier', models.CharField(help_text='RCL, NCL, MSC, CCL, VV, Others', max_length=20)),
                ('amount_per_pax_usd', models.DecimalField(decimal_places=2, help_text='USD por pasajero', max_digits=10)),
                ('minimum_charge_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='docking.port')),
            ],
            options={
                'verbose_name': 'Tarifa portuaria',
                'verbose_name_plural': 'Tarifas portuarias',
                'ordering': ['port', 'fee_tier'],
                'unique_together': {('port', 'fee_tier')},
            },
        ),
    ]
