# Generated by Django 6.0.6 on 2026-06-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('commercial_name', models.CharField(blank=True, help_text='Commercial or terminal name (e.g. Taino Bay for Puerto Plata).', max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('in_development', 'In development'), ('planned_extension', 'Planned extension')], default='operational', max_length=32)),
                ('is_mvp_scope', models.BooleanField(default=True, help_text='True for the six Booking MVP ports per minuta; False for out-of-scope ports.')),
                ('min_berth_draft_m', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum depth at berth line (m); doc §2 master table.', max_digits=5, null=True)),
                ('anchorage_slot_count', models.PositiveSmallIntegerField(default=0, help_text='Anchorage positions at port level (e.g. Roatán A1/A2).')),
                ('largest_vessel_recorded', models.CharField(blank=True, max_length=128)),
                ('largest_vessel_loa_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MooringScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vessel_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_projection', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mooring_scenarios', to='catalogs.port')),
            ],
            options={
                'ordering': ['port', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('walkway_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('walkway_width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_draft_m', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides port min_berth_draft_m when set.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berths', to='catalogs.port')),
            ],
            options={
                'ordering': ['port', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('position_type', models.CharField(choices=[('pier', 'Pier'), ('anchorage', 'Anchorage')], max_length=16)),
                ('max_loa_m', models.DecimalField(blank=True, decimal_places=2, help_text='Max LOA for this slot in current mooring layout.', max_digits=6, null=True)),
                ('min_draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('out_of_service', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_projection', models.BooleanField(default=False, help_text='Future-phase capacity; not current operational state (doc §5.4).')),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('berth', models.ForeignKey(blank=True, help_text='Null for anchorage-only positions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='catalogs.berth')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='catalogs.port')),
            ],
            options={
                'ordering': ['port', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MooringScenarioSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_label', models.CharField(blank=True, max_length=32)),
                ('max_loa_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalogs.mooringscenario')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mooring_slots', to='catalogs.position')),
            ],
            options={
                'ordering': ['scenario', 'sort_order', 'slot_label'],
            },
        ),
        migrations.AddConstraint(
            model_name='berth',
            constraint=models.UniqueConstraint(fields=('port', 'code'), name='uniq_berth_code_per_port'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('port', 'code'), name='uniq_position_code_per_port'),
        ),
    ]
