# Generated by Django 6.0.6 on 2026-06-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_seed_port_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='is_mvp_scope',
        ),
    ]
