# Generated by Django 6.0.6 on 2026-06-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_remove_port_is_mvp_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_lines', to='catalogs.shippinglinegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vessel_class', models.CharField(blank=True, max_length=128)),
                ('gross_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pax_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('crew_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('loa_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('beam_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('flag', models.CharField(blank=True, max_length=64)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, max_length=64)),
                ('size_category', models.CharField(blank=True, max_length=64)),
                ('mooring_line_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bollard_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bollard_swl_t', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vessels', to='catalogs.shippingline')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='shippingline',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='catalogs_shippingline_group_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.UniqueConstraint(fields=('shipping_line', 'name'), name='catalogs_vessel_line_name_uniq'),
        ),
    ]
