# Generated by Django 6.0.6 on 2026-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_seed_cruise_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bollard_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bollards (bitas) at this position.', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='fender_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of fenders (defensas) at this position.', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='max_loa_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max LOA (eslora) for this slot (m).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='min_draft_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Min depth / calado at berth line (m).', max_digits=5, null=True),
        ),
    ]
