# Generated by Django 6.0.6 on 2026-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_position_bollards_fenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='logo',
            field=models.ImageField(blank=True, help_text='Port logo thumbnail (single image).', null=True, upload_to='ports/logos/'),
        ),
    ]
