# Generated by Django 6.0.6 on 2026-06-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_port_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='fender_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total fenders at port level (docs §2 / §4 inventory).', null=True),
        ),
        migrations.CreateModel(
            name='PortBollard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_t', models.PositiveSmallIntegerField(help_text='Bollard capacity in metric tons (50, 75, 100, 150, 200, …).')),
                ('bollard_type', models.CharField(choices=[('standard', 'Standard'), ('t_head', 'T-head'), ('quick_release', 'Quick release hook'), ('single_bitt', 'Single bitt'), ('other', 'Other')], default='standard', max_length=32)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(blank=True, help_text='Optional label when type alone is not enough (e.g. Melilla variants).', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bollards', to='catalogs.port')),
            ],
            options={
                'ordering': ['sort_order', '-capacity_t', 'bollard_type'],
            },
        ),
        migrations.CreateModel(
            name='PortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ports/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False, help_text='Featured image in port gallery (logo remains the grid thumbnail).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogs.port')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PositionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='positions/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False, help_text='Cover image shown on position cards.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogs.position')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
