# Generated by Django 6.0.6 on 2026-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0015_position_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingline",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Shipping line logo thumbnail (single image).",
                null=True,
                upload_to="shipping_lines/logos/",
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Vessel image thumbnail (single image).",
                null=True,
                upload_to="vessels/logos/",
            ),
        ),
    ]
