# Generated by Django 6.0.6 on 2026-07-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0021_position_inventory_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_beam_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max beam (manga) for this slot (m).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='min_eta',
            field=models.TimeField(blank=True, help_text='Earliest recommended ETA for this position (warning if earlier).', null=True),
        ),
        migrations.CreateModel(
            name='PositionPairConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_loa_combined', models.DecimalField(decimal_places=2, help_text='Green threshold: sum of LOAs at or below this is fine (m).', max_digits=7)),
                ('max_loa_hard_cap', models.DecimalField(decimal_places=2, help_text='Red threshold: sum at or above this is a hard-cap warning (m).', max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_pair_constraints', to='catalogs.port')),
                ('position_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_constraints_as_a', to='catalogs.position')),
                ('position_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_constraints_as_b', to='catalogs.position')),
            ],
            options={
                'ordering': ['port', 'position_a', 'position_b'],
                'constraints': [models.UniqueConstraint(fields=('port', 'position_a', 'position_b'), name='uniq_position_pair_constraint'), models.CheckConstraint(condition=models.Q(('position_a', models.F('position_b')), _negated=True), name='position_pair_distinct')],
            },
        ),
    ]
