# Generated by Django 6.0.6 on 2026-07-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0030_enrich_melilla_layouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionNestingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_eta', models.BooleanField(default=True, help_text='Require inner ETA >= outer ETA when both occupy the same day.')),
                ('enforce_etd', models.BooleanField(default=True, help_text='Require inner ETD <= outer ETD when both occupy the same day.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inner_position', models.ForeignKey(help_text='Fondo / last-out position (must not arrive before outer).', on_delete=django.db.models.deletion.CASCADE, related_name='nesting_as_inner', to='catalogs.position')),
                ('outer_position', models.ForeignKey(help_text='Entrance / first-in position (must arrive first).', on_delete=django.db.models.deletion.CASCADE, related_name='nesting_as_outer', to='catalogs.position')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_nesting_rules', to='catalogs.port')),
            ],
            options={
                'ordering': ['port', 'outer_position', 'inner_position'],
                'constraints': [models.UniqueConstraint(fields=('port', 'outer_position', 'inner_position'), name='uniq_position_nesting_rule'), models.CheckConstraint(condition=models.Q(('outer_position', models.F('inner_position')), _negated=True), name='position_nesting_distinct')],
            },
        ),
    ]
