# Generated by Django 6.0.6 on 2026-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0036_loa_recalc_drop_combined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='min_loa_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mega-ship threshold for combined slots: vessel LOA >= this value must use this slot (e.g. 365 m).', max_digits=6, null=True),
        ),
    ]
