# Generated by Django 6.0.6 on 2026-08-19 14:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0039_port_proximity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portproximity',
            name='speed_knots_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Knots used to compute travel time (hardcoded baseline).', max_digits=6),
        ),
    ]
