# Generated by Django 6.0.6 on 2026-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0040_alter_portproximity_speed_knots_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionloarecalcrule',
            name='red_from_m',
            field=models.DecimalField(decimal_places=2, help_text='Both LOAs + separation at or above this is red (m).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='positionloarecalcrule',
            name='yellow_from_m',
            field=models.DecimalField(decimal_places=2, help_text='Both LOAs + separation at or above this is yellow (m).', max_digits=7),
        ),
    ]
