# Generated by Django 6.0.6 on 2026-08-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_username', models.CharField(max_length=150)),
                ('subject_display', models.CharField(blank=True, default='', max_length=255)),
                ('subject_role', models.CharField(blank=True, default='', max_length=32)),
                ('subject_is_active', models.BooleanField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_as_actor', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='User the event is about (null if deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_usera_created_a336cc_idx'), models.Index(fields=['action', '-created_at'], name='audit_usera_action_a1dd0c_idx'), models.Index(fields=['subject_role', '-created_at'], name='audit_usera_subject_ff7909_idx')],
            },
        ),
    ]
