# Generated by Django 6.0.6 on 2026-08-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_user_audit_entry'),
        ('bookings', '0012_booking_import_batch_retry_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingauditentry',
            name='booking_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bookingauditentry',
            name='port_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Port snapshot for ACL filters after booking deletion.', null=True),
        ),
        migrations.AlterField(
            model_name='bookingauditentry',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='bookings.booking'),
        ),
    ]
