# Generated by Django 6.0.6 on 2026-08-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_backfill_booking_audit_snapshots'),
        ('bookings', '0012_booking_import_batch_retry_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LtaAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_code', models.CharField(blank=True, default='', max_length=64)),
                ('agreement_name', models.CharField(blank=True, default='', max_length=255)),
                ('port_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('port_code', models.CharField(blank=True, default='', max_length=64)),
                ('shipping_line_code', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lta_audit_as_actor', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='bookings.longtermagreement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_ltaau_created_92218f_idx'), models.Index(fields=['action', '-created_at'], name='audit_ltaau_action_194201_idx'), models.Index(fields=['agreement_code', '-created_at'], name='audit_ltaau_agreeme_cf5a73_idx')],
            },
        ),
    ]
