# Generated by Django 6.0.6 on 2026-08-03 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_lta_audit_entry'),
        ('catalogs', '0032_seed_pop_filo_nesting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_port_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('port_code', models.CharField(blank=True, default='', max_length=64)),
                ('port_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_audit_as_actor', to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='catalogs.port')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_porta_created_6a0491_idx'), models.Index(fields=['action', '-created_at'], name='audit_porta_action_565dcb_idx'), models.Index(fields=['port_code', '-created_at'], name='audit_porta_port_co_af4bef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShippingLineAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_line_code', models.CharField(blank=True, default='', max_length=64)),
                ('shipping_line_name', models.CharField(blank=True, default='', max_length=255)),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_line_audit_as_actor', to=settings.AUTH_USER_MODEL)),
                ('shipping_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='catalogs.shippingline')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_shipp_created_602f37_idx'), models.Index(fields=['action', '-created_at'], name='audit_shipp_action_d4e531_idx'), models.Index(fields=['shipping_line_code', '-created_at'], name='audit_shipp_shippin_987289_idx')],
            },
        ),
    ]
