# Generated by Django 6.0.6 on 2026-06-22 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0015_position_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('booking_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalogs.port')),
                ('shipping_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalogs.shippingline')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalogs.vessel')),
            ],
            options={
                'ordering': ['-call_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('port', 'vessel', 'call_date'), name='bookings_unique_port_vessel_call_date')],
            },
        ),
    ]
