# Generated by Django 6.0.6 on 2026-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='eta_real',
            field=models.TimeField(blank=True, help_text='Actual time of arrival (set when closing to Real).', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='etd_real',
            field=models.TimeField(blank=True, help_text='Actual time of departure (set when closing to Real).', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('nr', 'New Request'), ('h', 'Hold'), ('co', 'Confirmed'), ('r', 'Real'), ('c', 'Cancelled')], default='nr', max_length=20),
        ),
    ]
