# Generated by Django 6.0.6 on 2026-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_map_booking_status_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('nr', 'New Request'), ('h', 'Hold'), ('co', 'Confirmed'), ('cl', 'Confirmed LTA'), ('lta', 'LTA'), ('ltd', 'Long Term Deployment'), ('r', 'Real'), ('c', 'Cancelled')], default='nr', max_length=20),
        ),
    ]
