# Generated by Django 6.0.6 on 2026-07-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_status_cl_lta_ltd'),
        ('catalogs', '0032_seed_pop_filo_nesting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('all_vessels', models.BooleanField(default=True, help_text='If true, all vessels of the shipping line are covered.')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='ISO weekdays Mon=0 … Sun=6. Empty = every day.')),
                ('min_packs', models.PositiveIntegerField(blank=True, help_text='Minimum packs to fulfill (stored; not enforced in phase 1).', null=True)),
                ('advance_months_min', models.PositiveSmallIntegerField(default=18, help_text='Far horizon starts (months ahead). Non-LTA blocked in this window.')),
                ('advance_months_max', models.PositiveSmallIntegerField(default=32, help_text='Maximum months ahead this LTA may book.')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='long_term_agreements', to='catalogs.port')),
                ('positions', models.ManyToManyField(blank=True, help_text='Pier positions covered by this agreement (e.g. P1).', related_name='long_term_agreements', to='catalogs.position')),
                ('shipping_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='long_term_agreements', to='catalogs.shippingline')),
                ('vessels', models.ManyToManyField(blank=True, help_text='Specific vessels when all_vessels is false.', related_name='long_term_agreements', to='catalogs.vessel')),
            ],
            options={
                'ordering': ['port', 'shipping_line', 'code'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='long_term_agreement',
            field=models.ForeignKey(blank=True, help_text='Linked LTA when the call uses the LTA track.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.longtermagreement'),
        ),
    ]
