# Generated by Django 6.0.6 on 2026-07-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_long_term_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermagreement',
            name='contract_file',
            field=models.FileField(blank=True, help_text='Optional contract attachment (PDF/DOC).', null=True, upload_to='bookings/lta_contracts/'),
        ),
    ]
