# Generated by Django 6.0.6 on 2026-07-30 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_lta_contract_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('file', 'Archivo'), ('paste', 'Pegado')], default='file', max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completada')], default='completed', max_length=16)),
                ('requested_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_booking_ids', models.JSONField(blank=True, default=list)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking import batch',
                'verbose_name_plural': 'booking import batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
