# Generated by Django 6.0.6 on 2026-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingimportbatch',
            name='retry_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
