# Generated by Django 6.0.6 on 2026-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_lta_booking_policy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermagreement',
            name='bookings_generated',
            field=models.BooleanField(default=False, help_text='True after the first successful Generar (or Regenerar) run.'),
        ),
    ]
