# Generated by Django 6.0.6 on 2026-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_lta_bookings_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_manifest',
            field=models.FileField(blank=True, help_text='Arrival manifest uploaded by port operator (PDF/image).', null=True, upload_to='bookings/arrival_manifests/'),
        ),
    ]
