# Generated by Django 6.0.6 on 2026-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_booking_arrival_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='operation_notes',
            field=models.TextField(blank=True, help_text='Port-operator notes for arrival / berth operations (not identity notes).'),
        ),
    ]
