# Generated by Django 6.0.6 on 2026-09-06 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_lta_date_exceptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_tags_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking tag',
                'verbose_name_plural': 'booking tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingRunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mass_update', 'Actualización masiva'), ('lta_generate', 'Creación LTA'), ('lta_agreement', 'Actualización acuerdos LTA')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=255)),
                ('booking_ids', models.JSONField(blank=True, default=list)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Process context (agreement_code, job_kind, …).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_run_batches', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, help_text='Only used for mass_update runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_batches', to='bookings.bookingtag')),
            ],
            options={
                'verbose_name': 'booking run batch',
                'verbose_name_plural': 'booking run batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Optional operator tag for filtering related bookings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingtag'),
        ),
        migrations.AddField(
            model_name='bookingimportbatch',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Optional tag applied to bookings created in this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='bookings.bookingtag'),
        ),
    ]
