# Generated by Django 6.0.6 on 2026-09-01 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('conflict_detected', 'Conflict detected'), ('conflict_resolved', 'Conflict resolved'), ('conflict_updated', 'Conflict updated')], max_length=32)),
                ('artifact', models.CharField(blank=True, choices=[('wizard', 'Wizard'), ('mass_import', 'Mass import'), ('mass_update', 'Mass update'), ('lta_generate', 'LTA generate'), ('lta_agreement', 'LTA agreement'), ('berthing_import', 'Berthing import'), ('conflict', 'Conflict')], default='', max_length=32)),
                ('target', models.CharField(choices=[('booking_detail', 'Booking detail'), ('bookings_history', 'Bookings history')], max_length=32)),
                ('message', models.CharField(max_length=512)),
                ('actor_display', models.CharField(blank=True, default='', max_length=150)),
                ('booking_id', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_code', models.CharField(blank=True, default='', max_length=64)),
                ('port_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('batch_id', models.PositiveIntegerField(blank=True, null=True)),
                ('affected_count', models.PositiveIntegerField(default=1)),
                ('history_type_filter', models.CharField(blank=True, default='', max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
